git_repo: "https://github.com/mcyliowski/helm_charts.git"
dest_dir: /tmp/poe-woc
chart_ref: /tmp/poe-woc/poe_wheel_of_choice
chart_dir: /tmp/linux-amd64
url: "https://get.helm.sh/helm-v3.13.1-linux-amd64.tar.gz"
file: /tmp/helm-v3.13.1-linux-amd64.tar.gz
config: /etc/kubernetes/admin.conf